version: "3"

services:
    jenkins:
        image: jenkins/jenkins:lts
        volumes:
            - ./data:/var/jenkins_home 
            - /var/run/docker.sock:/var/run/docker.sock

        ports:
            - 8080:8080
            - 50000:50000
